version: '3'
services:
  api:
    build: .
    ports:
      - 8000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development # se quiser pode por essa variável de ambiente
    volumes:
      - ${PWD}/api-container/:/var/lib/api/
    depends_on:
      - mssql
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - ${PWD}/mssql-server/:/var/lib/mssql/    
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: cav@1324