version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/dockerfile.yml
    image: cavaleras-backend-docker
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development # se quiser pode por essa variável de ambiente
    volumes:
      - .:/src
    depends_on:
      - mssql
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - 11433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: cavaleras(!)cav@3215